version: '3.4'

services:
  ui:
    container_name: webapp_container
    image: ${DOCKER_REGISTRY-}ui
    build:
      context: .
      dockerfile: UI/Dockerfile
    ports:
      - "5000:443"
    env_file:
      - ui.env
    depends_on:
      - api
  api:
    container_name: api_container
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5001:443"
    env_file:
      - api.env
    depends_on:
      - db
  db:
    container_name: db_container
    image:  "mcr.microsoft.com/mssql/server"
    hostname: sql-server
    ports:
      - "1433:1433"
    env_file:
      - db.env
    volumes:
      - mssql_db:/var/opt/mssql

volumes:
  mssql_db: {}