version: '3.4'

services:
  ui:
    container_name: webapp_container
    image: ${DOCKER_REGISTRY-}ui
    build:
      context: .
      dockerfile: UI/Dockerfile
    ports:
      - "5000:443"
    depends_on:
      - api
      - db
  api:
    container_name: api_container
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5001:443"
    depends_on:
      - db
  db:
    container_name: db_container
    image:  "mcr.microsoft.com/mssql/server:2019-latest"
    hostname: sql-server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1